// rAthena msg_athena.conf
// การตั้งค่าข้อความของ login-server
// -----------------------
0: ไอดีนี้ยังไม่ได้ลงทะเบียน
1: รหัสผ่านไม่ถูกต้อง
2: บัญชีหมดอายุแล้ว
3: การเชื่อมต่อถูกปฏิเสธจากเซิร์ฟเวอร์
4: บัญชีถูกระงับโดยทีมงาน GM
5: เวอร์ชั่นของตัวเกม (EXE) ไม่ถูกต้อง
6: บัญชีถูกแบน
7: เซิร์ฟเวอร์เต็ม (มีผู้เล่นหนาแน่นเกินไป)
8: บัญชีถึงขีดจำกัดตามเงื่อนไขของบริษัท
9: บัญชีถูกระงับโดยผู้ดูแลฐานข้อมูล (DBA)
10: ยังไม่ได้ยืนยันอีเมล
11: บัญชีถูกแบนโดย GM
12: ฐานข้อมูลกำลังอยู่ระหว่างการปรับปรุง
13: บัญชีถูกล็อค (Self Lock)
14: กลุ่มผู้ใช้งานไม่ได้รับอนุญาต
15: กลุ่มผู้ใช้งานไม่ได้รับอนุญาต
16: บัญชีนี้ถูกลบออกจากระบบแล้ว
17: ข้อมูลการล็อกอินยังคงค้างอยู่ในระบบ
18: อยู่ระหว่างการตรวจสอบการแฮกข้อมูล
19: อยู่ระหว่างการตรวจสอบบั๊กของระบบ
20: อยู่ระหว่างการลบตัวละคร
21: อยู่ระหว่างการลบตัวละครที่มีคู่รัก
22: เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุ