ALTER TABLE `login` ADD COLUMN `last_hwid` VARCHAR(50) NOT NULL DEFAULT '';

CREATE TABLE `hwid_bans` (
  `hwid` VARCHAR(50) NOT NULL,
  `ban_reason` VARCHAR(255) NOT NULL DEFAULT 'Banned by Admin',
  `ban_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`hwid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `hwid_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `account_id` INT(11) NOT NULL,
  `hwid` VARCHAR(64) NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;