ALTER TABLE `char` MODIFY `name` VARCHAR(70) NOT NULL DEFAULT '';
ALTER TABLE `guild` MODIFY `name` VARCHAR(70) NOT NULL DEFAULT '';
ALTER TABLE `party` MODIFY `name` VARCHAR(70) NOT NULL DEFAULT '';
ALTER TABLE `pet` MODIFY `name` VARCHAR(70) NOT NULL DEFAULT '';
ALTER TABLE `homunculus` MODIFY `name` VARCHAR(70) NOT NULL DEFAULT '';